# Generated by Django 6.0.7 on 2026-07-17 02:42

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('company_name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(blank=True)),
                ('tax_id', models.CharField(blank=True, max_length=60)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60, unique=True)),
                ('abbreviation', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('manager', 'Warehouse Manager'), ('staff', 'Warehouse Staff'), ('requester', 'Requesting Department'), ('auditor', 'Auditor / Viewer')], default='staff', max_length=20)),
                ('employee_id', models.CharField(blank=True, max_length=30)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('is_active_employee', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=150)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('object_id', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DamageReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_number', models.CharField(max_length=100, unique=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reason', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='damage/')),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('approved', 'Approved'), ('disposed', 'Disposed'), ('rejected', 'Rejected')], default='reported', max_length=15)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='damage_reports_approved', to=settings.AUTH_USER_MODEL)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='damage_reports_filed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_number', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('counting', 'Counting'), ('for_review', 'For Review'), ('approved', 'Approved'), ('closed', 'Closed')], default='open', max_length=15)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.category')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='counts_created', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counts_reviewed', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_counts', to='backend.warehouse')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_number', models.CharField(max_length=100, unique=True)),
                ('department', models.CharField(max_length=120)),
                ('purpose', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('released', 'Released'), ('partially_released', 'Partially Released'), ('cancelled', 'Cancelled')], default='pending', max_length=25)),
                ('approval_remarks', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_requests_approved', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_target', models.CharField(blank=True, help_text='Send to all users of this role instead of one user', max_length=20)),
                ('message', models.CharField(max_length=255)),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('danger', 'Danger')], default='info', max_length=10)),
                ('link', models.CharField(blank=True, max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('tracking_type', models.CharField(choices=[('quantity', 'Quantity-Based'), ('individual', 'Individual Asset')], default='quantity', max_length=20)),
                ('brand', models.CharField(blank=True, max_length=120)),
                ('barcode', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('minimum_stock', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('maximum_stock', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('reorder_level', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('qr_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='backend.category')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='backend.unit')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ItemRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_requested', models.DecimalField(decimal_places=2, max_digits=14)),
                ('quantity_released', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='backend.itemrequest')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.product')),
            ],
        ),
        migrations.CreateModel(
            name='Disposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_number', models.CharField(max_length=100, unique=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=14)),
                ('method', models.CharField(choices=[('scrap', 'Scrap'), ('donate', 'Donate'), ('sell', 'Sell'), ('recycle', 'Recycle'), ('return_to_supplier', 'Return to Supplier'), ('destroy', 'Destroy')], max_length=25)),
                ('witnesses', models.CharField(blank=True, max_length=255)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disposals_approved', to=settings.AUTH_USER_MODEL)),
                ('damage_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disposals', to='backend.damagereport')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='damagereport',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='damage_reports', to='backend.product'),
        ),
        migrations.CreateModel(
            name='ProductBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_number', models.CharField(max_length=100)),
                ('manufacturing_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('qr_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='backend.product')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.supplier')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='damagereport',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.productbatch'),
        ),
        migrations.CreateModel(
            name='Receiving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_number', models.CharField(max_length=100, unique=True)),
                ('purchase_order', models.CharField(blank=True, max_length=100)),
                ('delivery_receipt', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('for_inspection', 'For Inspection'), ('partially_accepted', 'Partially Accepted'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('stored', 'Stored')], default='draft', max_length=25)),
                ('remarks', models.TextField(blank=True)),
                ('inspected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receivings_inspected', to=settings.AUTH_USER_MODEL)),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receivings_done', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receivings', to='backend.supplier')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receivings', to='backend.warehouse')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_number', models.CharField(max_length=100, unique=True)),
                ('department', models.CharField(blank=True, max_length=120)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed')], default='pending', max_length=15)),
                ('returned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns_filed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=14)),
                ('condition', models.CharField(choices=[('good', 'Good'), ('used', 'Used'), ('damaged', 'Damaged'), ('for_repair', 'For Repair'), ('condemned', 'Condemned'), ('missing_parts', 'Missing Parts')], default='good', max_length=20)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.productbatch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.product')),
                ('return_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='backend.return')),
            ],
        ),
        migrations.CreateModel(
            name='StockRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_number', models.CharField(max_length=100, unique=True)),
                ('released_to_department', models.CharField(max_length=120)),
                ('recipient_name', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('released', 'Released'), ('confirmed', 'Confirmed')], default='draft', max_length=15)),
                ('remarks', models.TextField(blank=True)),
                ('item_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='releases', to='backend.itemrequest')),
                ('released_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='releases_done', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockReleaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=14)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.productbatch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.product')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='backend.stockrelease')),
            ],
        ),
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_number', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('in_transit', 'In Transit'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_approved', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_requested', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockTransferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=14)),
                ('is_processed', models.BooleanField(default=False)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.productbatch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.product')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='backend.stocktransfer')),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=150)),
                ('location_type', models.CharField(choices=[('zone', 'Zone'), ('rack', 'Rack'), ('shelf', 'Shelf'), ('bin', 'Bin')], default='bin', max_length=10)),
                ('qr_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='backend.warehouselocation')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='backend.warehouse')),
            ],
            options={
                'ordering': ['warehouse', 'code'],
            },
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='destination_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='backend.warehouselocation'),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='source_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='backend.warehouselocation'),
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_number', models.CharField(db_index=True, max_length=100)),
                ('transaction_type', models.CharField(choices=[('receive', 'Receive'), ('release', 'Release'), ('transfer_in', 'Transfer In'), ('transfer_out', 'Transfer Out'), ('return', 'Return'), ('adjustment_in', 'Adjustment In'), ('adjustment_out', 'Adjustment Out'), ('damage', 'Damage'), ('disposal', 'Disposal')], max_length=30)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=14)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=14)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='backend.productbatch')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_transactions', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='backend.product')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='backend.warehouselocation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='stockrelease',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='releases', to='backend.warehouselocation'),
        ),
        migrations.CreateModel(
            name='StockBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_balances', to='backend.productbatch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_balances', to='backend.product')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_balances', to='backend.warehouselocation')),
            ],
            options={
                'ordering': ['product__name'],
            },
        ),
        migrations.AddField(
            model_name='return',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='backend.warehouselocation'),
        ),
        migrations.CreateModel(
            name='ReceivingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(blank=True, max_length=100)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('quantity_ordered', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('quantity_received', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('quantity_accepted', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('quantity_rejected', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_stored', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.product')),
                ('receiving', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='backend.receiving')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.warehouselocation')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryCountItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('counted_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('matched', 'Matched'), ('for_investigation', 'For Investigation'), ('adjusted', 'Adjusted')], default='pending', max_length=20)),
                ('counted_at', models.DateTimeField(blank=True, null=True)),
                ('count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='backend.inventorycount')),
                ('counted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.product')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='backend.productbatch')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.warehouselocation')),
            ],
        ),
        migrations.AddField(
            model_name='inventorycount',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_counts', to='backend.warehouselocation'),
        ),
        migrations.AddField(
            model_name='damagereport',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.warehouselocation'),
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_code', models.CharField(max_length=30, unique=True)),
                ('serial_number', models.CharField(blank=True, max_length=150)),
                ('condition', models.CharField(choices=[('good', 'Good'), ('fair', 'Fair'), ('for_repair', 'For Repair'), ('damaged', 'Damaged'), ('condemned', 'Condemned')], default='good', max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available'), ('assigned', 'Assigned'), ('in_repair', 'In Repair'), ('disposed', 'Disposed'), ('missing', 'Missing')], default='available', max_length=20)),
                ('qr_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_assets', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='backend.product')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='backend.warehouselocation')),
            ],
            options={
                'ordering': ['asset_code'],
            },
        ),
        migrations.AddConstraint(
            model_name='productbatch',
            constraint=models.UniqueConstraint(fields=('product', 'batch_number'), name='unique_batch_per_product'),
        ),
        migrations.AddConstraint(
            model_name='warehouselocation',
            constraint=models.UniqueConstraint(fields=('warehouse', 'code'), name='unique_location_code_per_warehouse'),
        ),
        migrations.AddConstraint(
            model_name='stockbalance',
            constraint=models.UniqueConstraint(fields=('product', 'batch', 'location'), name='unique_product_batch_location_balance'),
        ),
    ]
