# Generated by Django 6.0.7 on 2026-07-22 05:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GRDSItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_no', models.CharField(help_text="GRDS Item No. as printed in the schedule, e.g. 'SSSRDS 9', '74', '26'.", max_length=30, unique=True)),
                ('records_series_title', models.CharField(max_length=255)),
                ('retention_period', models.CharField(help_text="Free text as GRDS defines it, e.g. '1 YEAR', '10 YEARS POST-AUDITED, FINALLY SETTLED...', or 'TO BE FILED WITH APPROPRIATE RECORDS SERIES'.", max_length=150)),
                ('is_commonly_used', models.BooleanField(default=False, help_text="Appears on the branch's BRANCH COMMONLY USED ITEMS shortlist.")),
                ('default_scanning_status', models.CharField(blank=True, choices=[('scanned', 'Scanned'), ('unscanned', 'Unscanned'), ('not_applicable', 'Not Applicable')], max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['item_no'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ArchiveBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_type', models.CharField(choices=[('archiving', 'Archiving'), ('disposal', 'Disposal')], max_length=10)),
                ('reference_no', models.CharField(db_index=True, help_text="Grouping reference for the whole box batch, e.g. 'H02-23-001' or 'ARCH-24-001'.", max_length=50)),
                ('box_number', models.CharField(help_text="'BOX #' — kept as text since the sheet has values like '45-1'.", max_length=20)),
                ('batch_no', models.CharField(help_text="Unique per-item batch code, e.g. 'H02-23-0011' (REFERENCE NO + BOX #).", max_length=50, unique=True)),
                ('batch_date', models.DateField()),
                ('grds_item_no_raw', models.CharField(blank=True, help_text="Fallback copy of the sheet's GRDS ITEM NO text when it didn't match the catalog.", max_length=30)),
                ('description', models.CharField(max_length=255)),
                ('period_covered', models.CharField(blank=True, help_text="Free text as written on the sheet, e.g. '2015-2018' or 'JAN-DEC 2016'.", max_length=255)),
                ('latest_year', models.PositiveIntegerField(blank=True, null=True)),
                ('years_as_of_count', models.IntegerField(blank=True, help_text="'NO. YEARS AS OF <year>' column.", null=True)),
                ('retention_period_years', models.PositiveIntegerField(blank=True, help_text="Numeric retention period used for the batch's own math.", null=True)),
                ('disposal_status_value', models.IntegerField(blank=True, help_text="The sheet's 'STATUS (GREEN: for DISPOSAL)' value: years_as_of_count minus retention_period_years. Zero or positive generally means it's eligible.", null=True)),
                ('scanning_status', models.CharField(blank=True, choices=[('scanned', 'Scanned'), ('unscanned', 'Unscanned'), ('not_applicable', 'Not Applicable')], max_length=20)),
                ('location', models.CharField(blank=True, help_text="Current whereabouts/disposition, e.g. 'DISPOSED THRU NAP', 'RIMS CDO'.", max_length=150)),
                ('remarks', models.TextField(blank=True)),
                ('linked_batch', models.ForeignKey(blank=True, help_text="Cross-reference to the corresponding row in the other sheet: on a DISPOSAL batch, points at the ARCHIVING batch it came from ('BATCH NO FROM ARCHIVES'); on an ARCHIVING batch, points at the DISPOSAL batch it graduated to once processed.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_batches', to='records.archivebatch')),
                ('grds_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='records.grdsitem')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='records.section')),
            ],
            options={
                'verbose_name_plural': 'Archive batches',
                'ordering': ['-batch_date', 'reference_no'],
            },
        ),
        migrations.CreateModel(
            name='DisposalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_no', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted to NAP'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=15)),
                ('request_date', models.DateField()),
                ('agency_name', models.CharField(default='SOCIAL SECURITY SYSTEM', max_length=200)),
                ('branch_name', models.CharField(blank=True, max_length=150)),
                ('address', models.TextField(blank=True)),
                ('telephone_number', models.CharField(blank=True, max_length=30)),
                ('email_address', models.EmailField(blank=True, max_length=254)),
                ('location_of_records', models.CharField(blank=True, max_length=200)),
                ('volume_boxes', models.PositiveIntegerField(blank=True, null=True)),
                ('volume_cubic_meters', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('prepared_by_position', models.CharField(blank=True, max_length=150)),
                ('remarks', models.TextField(blank=True)),
                ('batches', models.ManyToManyField(blank=True, limit_choices_to={'batch_type': 'disposal'}, related_name='disposal_requests', to='records.archivebatch')),
                ('noted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disposal_requests_noted', to=settings.AUTH_USER_MODEL)),
                ('prepared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disposal_requests_prepared', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-request_date'],
            },
        ),
        migrations.AddField(
            model_name='grdsitem',
            name='default_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grds_items', to='records.section'),
        ),
    ]
