# Generated by Django 6.0.7 on 2026-07-28 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_archivebatch_qr_token_step3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivebatch',
            name='location',
            field=models.CharField(blank=True, choices=[('rims_cdo', 'RIMS CDO'), ('archive_room', 'Archive Room'), ('branch_stockroom', 'Branch Stockroom'), ('offsite_storage', 'Offsite Storage'), ('disposed_thru_nap', 'Disposed thru NAP')], help_text='Current whereabouts/disposition.', max_length=150),
        ),
    ]
